//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Productions = new HashSet<Production>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string article { get; set; }
        public Nullable<int> min_price_agent { get; set; }
        public string image { get; set; }
        public Nullable<int> type_product { get; set; }
        public Nullable<int> min_amount_people { get; set; }
        public Nullable<int> guild { get; set; }
        public Nullable<int> width_product { get; set; }
        public Nullable<int> lenght_product { get; set; }
    
        public virtual Guild Guild1 { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Productions { get; set; }
    }
}
