//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int id_production { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> min_amount_material { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
